server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
          filters:
            - RewritePath=/course/(?<path>.*), /$\{path}
        - id: lesson-service
          uri: lb://lesson-service
          predicates:
            - Path=/lesson/**
          filters:
            - RewritePath=/lesson/(?<path>.*), /$\{path}
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - RewritePath=/profile/(?<path>.*), /$\{path}
        - id: university-service
          uri: lb://university-service
          predicates:
            - Path=/university/**
          filters:
            - RewritePath=/university/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"